# -- Main Menu --

[[main]]
  name = "About"
  url = "/#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "/#publications"
  weight = 20

[[main]]
  name = "Awards"
  url = "/#awards"
  weight = 30

[[main]]
  name = "CV"
  url = "/cv.pdf"
  weight = 40

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 50
